### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by thekonz** [orkhanahmadov/laravel-accept-language-middleware#7]
It's that time of the year again ;)

The job [failed](https://github.com/orkhanahmadov/laravel-accept-language-middleware/actions/runs/4097815769/jobs/7066463396) on february 5th, because [illuminate/contracts v10](https://packagist.org/packages/illuminate/contracts#v10.0.0) was released on february 14th.

Maybe trigger the build again and release. Pretty please :)

If you can't be bothered, I would do it, if you want to add me to the repo.

**Comment by orkhanahmadov** [comment]
Tagged [2.2.0](https://github.com/orkhanahmadov/laravel-accept-language-middleware/releases/tag/2.2.0)
